# Generated by Django 2.2.6 on 2020-04-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('UID', models.CharField(max_length=10)),
                ('frontEndChannelName', models.CharField(max_length=254)),
                ('backEndChannelName', models.CharField(max_length=254)),
            ],
        ),
    ]
