# Generated by Django 2.2.6 on 2020-07-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200507_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='websocketStatus',
            field=models.BooleanField(default=False),
        ),
    ]
