# Generated by Django 2.2.6 on 2020-08-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_account_websocketstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='intentAgentUserId',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
