# Generated by Django 2.2.6 on 2020-08-28 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_account_intentagentuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accessToken',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
